name: Render video
on:
  schedule:
    - cron: "0 5 * * *"
jobs:
  render:
    name: Render video and publish it
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - run: sudo apt update
      - run: sudo apt install ffmpeg
      - run: npm i
      - run: npm run ssr
      - uses: actions/upload-artifact@v2
        with:
          name: out.mp4
          path: out/daily-kanji.mp4
