name: Render video and publish it
on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:
jobs:
  render:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - run: sudo apt update
      - run: sudo apt install ffmpeg
      - run: npm run v
      - run: npm i
      - name: set env and start ssr
        run: npm run ssr
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          IG_USERNAME: ${{ secrets.IG_USERNAME }}
          IG_PASSWORD: ${{ secrets.IG_PASSWORD }}
      - uses: actions/upload-artifact@v2
        with:
          name: out.mp4
          path: out/daily-kanji.mp4
